In [1]:
import numpy as np

# 1. Create 2D array (3,4) with random ints 0-10
arr = np.random.randint(0, 11, size=(3, 4))
print("Original:\n", arr)

# 2. Mean and Standard Deviation
print("Mean:", arr.mean(), "| Std Dev:", arr.std())

# 3. Slice: first 2 rows, last 2 columns
print("Sliced:\n", arr[:2, -2:])

# 4. Reshape to (4, 3)
reshaped = arr.reshape(4, 3)
print("Reshaped:\n", reshaped)

# 5. Element-wise multiplication with same shape
arr2 = np.random.randint(1, 5, size=(4, 3))
print("Multiplied:\n", reshaped * arr2)

Original:
 [[ 9  6  7  8]
 [ 3  2  1  9]
 [ 4  0 10 10]]
Mean: 5.75 | Std Dev: 3.467107343785787
Sliced:
 [[7 8]
 [1 9]]
Reshaped:
 [[ 9  6  7]
 [ 8  3  2]
 [ 1  9  4]
 [ 0 10 10]]
Multiplied:
 [[18  6 28]
 [16  3  6]
 [ 2  9 12]
 [ 0 40 30]]
